---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true
  force_handlers: true

  - name: update datafeed package
    yum:
      name: datafeed
      enablerepo: "datafeed"
      state: latest