---

- hosts: rhel9-3.lanathome.com
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  gather_subset: min

  vars:
    find_history_excluded: 
      - "/home/ansible/.bash_history"


  tasks:

  - name: Collect only selected facts
    ansible.builtin.setup:
      gather_subset: min

  - name: Empty output directory from previous run
    ansible.builtin.file:
      dest: /home/ngr/ansible_run/output/shell_history/
      state: absent

  - name: recursively find *_history files
    block:
    - name: Find files
      ansible.builtin.find:
        paths: '/home'
        patterns: '*_history'
        file_type: file
        hidden: yes
        recurse: yes
      register: find_history

    - name: Display the value type of find_history.files
      ansible.builtin.debug:
        msg: "find_history.files={{ find_history.files }} / Data type={{ find_history.files | type_debug }}"

    - name: display find_history_excluded
      ansible.builtin.debug:
        var: find_history_excluded # <--- Data type=list

    - name: Display the value type of find_history_excluded
      ansible.builtin.debug:
        msg: "find_history_excluded={{ find_history_excluded }} / Data type={{ find_history_excluded | type_debug }}"

    - name: Exclude specified files from the list
      set_fact:
        bash_history_files_filtered: "{{ find_history.files | rejectattr('path', 'in', find_history_excluded) | list }}"

    - name: Debug the filtered list of .bash_history files
      debug:
        var: bash_history_files_filtered

    - name: "Slurp found history files"
      ansible.builtin.slurp:
        src: '{{ item.path }}'
      register: files
      loop: "{{ bash_history_files_filtered }}"

#   - name: "display find_history.files"
#     ansible.builtin.debug:
#       var=find_history.files

#   - name: "display find_history.files[0]"
#     ansible.builtin.debug:
#       var=find_history.files[0].pw_name

    - name: Create empty output directory
      ansible.builtin.file:
        dest: /home/ngr/ansible_run/output/shell_history
        state: directory
        owner: ngr

    - name: "Loop of jinja template found history files"
      ansible.builtin.template:
        src: /Users/ngr/ansible_run/playbooks/history_files.j2
        dest: "/home/ngr/ansible_run/output/shell_history/{{ ansible_hostname }}.json"
      vars:
        - input: "{{ files.results }}"

    - name: Write results to local file
      ansible.builtin.fetch:
        src: /home/ngr/ansible_run/output/shell_history/{{ ansible_hostname }}.json
        dest: /Users/ngr/ansible_run/output/shell_history/{{ ansible_hostname }}.json
        flat: yes

