---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true
  force_handlers: true

  vars:
  
  tasks:

  - name: read facts 
    setup: filter=ansible_lvm
  
      # "ansible_facts": {
      #   "ansible_lvm": {
      #       "lvs": {
      #           "appli-controlm": {
      #               "size_g": "0.20",
      #               "vg": "rootvg"
      #           },
  - debug:
      msg: '{{ ansible_lvm["lvs"]["appli-controlm"]["vg"] }}'

  - set_fact:
      discovered_vg: '{{ ansible_lvm["lvs"]["appli-controlm"]["vg"] }}'

  - name: Extend the logical volume appli-controlm and resize the underlying filesystem
    lvol:
      vg: '{{ ansible_lvm["lvs"]["appli-controlm"]["vg"] }}'
      lv: appli-controlm
      size: 350m
      resizefs: true
      shrink: no
    when: ansible_lvm["lvs"]["appli-controlm"]["vg"] != ""

  - name: read facts again and display the new volume once increased
    setup: filter=ansible_lvm
  
      # "ansible_facts": {
      #   "ansible_lvm": {
      #       "lvs": {
      #           "appli-controlm": {
      #               "size_g": "7.0", <----- new filesystem appears here and should be 7g
      #               "vg": "rootvg"
      #           },
  - debug:
      msg: 'filesystem size once increased: {{ ansible_lvm["lvs"]["appli-controlm"] }}'