---
- hosts: docker01.lanathome.com,docker02.lanathome.com
  become: yes
  gather_facts: false

  tasks:

  - name: Find out what the remote machine's XFS mounts are 
    slurp:
      src: /proc/mounts
    register: mounts

  # - debug:
  #     msg: "{{ mounts['content'] | b64decode }}"

  - set_fact:
     xfs_mounts: "{{ mounts['content']|b64decode|trim|regex_findall('\\/dev\\/mapper\\/\\w{1,}\\-\\w{1,}') | list }}"

#regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}
#(\/\w{1,}\/(sd).[1-99]\s\/(\w{1,}|\W{1,})?\s(\bxfs\b))|(\/\w{1,}\/\w{1,}\/\w{1,}\-\w{1,})\s\/(\w{1,}|\W{1,})?\s(\bxfs\b)
#\/dev\/mapper\/\w{1,}\-\w{1,}

  - name: run xfs_fsr - filesystem reorganizer for XFS
    command: /sbin/xfs_fsr -v "{{ item }}"
    register: xfs_fsr_out_"{{ item }}"
    with_list: "{{ xfs_mounts }}"

  - name: retrieve output of xfs_fsr - filesystem reorganizer for XFS
    debug:
      msg: xfs_fsr returns "{{ xfs_fsr_out_\"{{ item }}\".stdout }}"
    with_list: "{{ xfs_mounts }}"