---

- hosts: xxxxx
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  gather_subset: min

  tasks:

  - name: Collect only selected facts
    ansible.builtin.setup:
      gather_subset: min

  - name: recursively find *_history files
    block:
    - name: Find files
      ansible.builtin.find:
        paths: '/home'
        patterns: '*_history'
        file_type: file
        hidden: yes
        recurse: yes
      register: find_history

    - name: Display the value type of find_history
      ansible.builtin.debug:
        msg: "find_history={{ find_history }} / Data type={{ find_history | type_debug }}"

    - name: "display find_history"
      ansible.builtin.debug:
        var=find_history # <--- Data type=dict

    - name: Display the value type of find_history.files
      ansible.builtin.debug:
        msg: "find_history.files={{ find_history.files }} / Data type={{ find_history.files | type_debug }}"

    - name: "display find_history.files"
      ansible.builtin.debug:
        var=find_history.files # <--- Data type=list

    - name: "list _history files"
      ansible.builtin.debug:
        var=item.path
      loop: "{{ find_history.files }}" # <--- Data type=list

    - name: "debug"
      ansible.builtin.debug:
        msg: "{{ find_history.files | map(attribute='path')}}"
