---
- hosts: docker\*
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true
  force_handlers: true

  vars:
  
  tasks:
  
  - name: exclude ansible package in /etc/yum.conf for alm hosts only
    lineinfile:
      path: /etc/yum.conf
      regexp: '^exclude='
      line: exclude=telnet
      insertafter: '^distroverpkg=centos-release'
    when: "'docker' in inventory_hostname"