---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true

  vars:
    user_prompted: root
    password_prompted: '$6$acR/H978lv776G3b$.cCmbxA1L4qUUk2I5PDFe8QzpPkkMnZpko6aBK7Ey9cCa84wSsI/y1uhOP.CX665X9qjlWUfAR/K8eqxDUF.M1'
  
  tasks:
  # - debug: var=ansible_facts

  - name: get root user info
    getent:
      database: passwd
      key: '{{ user_prompted }}'
      split: ':'
    register: userexists

  - name: set user password
    user:
      name: '{{ user_prompted }}'
      password: "{{ password_prompted | password_hash('sha512') }}"
      update_password: always
    when: "user_prompted in ansible_facts['getent_passwd']"
