---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true
  force_handlers: true

  vars:
    user_prompted: root
    password_prompted: '$6$acR/H978lv776G3b$.cCmbxA1L4qUUk2I5PDFe8QzpPkkMnZpko6aBK7Ey9cCa84wSsI/y1uhOP.CX665X9qjlWUfAR/K8eqxDUF.M1'
    ec2_security_group_names: []
  
  tasks:
  
  - name: get user info using getent with database passwd
    getent:
      database: passwd
      key: '{{ user_prompted }}'
      split: ':'
      fail_key: no
    register: user_info_linux

  - debug:
      var: ansible_facts['getent_passwd']

  - name: Handle the task failure if user does not exist

    block:
      - name: assert if user does exist or not
        assert:
          that:
            - user_info_linux.ansible_facts.getent_passwd.{{ user_prompted }} != None
          success_msg: "user exists on that host. resetting password"
          fail_msg: "user doesnt exist on this host. skipping"
      - name: set user password using ansible user module
        user:
          name: '{{ user_prompted }}'
          password: "{{ password_prompted | password_hash('sha512') }}"
          update_password: always
        when: "user_prompted in ansible_facts['getent_passwd']"
      - name: Build a list of all the servers where password reset occured
        register: ec2_security_groups
        notify: notify password recipient by email

    rescue:
      - debug:
          msg: 'user doesnt exist on this host. skipping'

  - name: Build a list of all the security group names.
    set_fact:
      ec2_security_group_names: "{{ ec2_security_group_names }} + [ '{{ item.group_name }}' ]"
      with_items: "{{ ec2_security_groups.security_groups }}"

  - name: Print the security group names to the console.
    debug: var=ec2_security_group_names

  handlers:
  - name: notify password recipient by email
    mail:
      host: awx01.lanathome.com
      port: 25
      from: '{{ mail_from }}'
      to: '{{ recipient_mailto }}'
      subject: Your password reset request
      headers:
        - Reply-To=no-reply@sfr.fr
      subtype: html
      body: As per your request your password for user <b>{{ user_prompted }}</b> has been successfully reset to  <b>{{ password_prompted }}</b> on  <b>{{ ansible_host }}</b>
    #delegate_to: localhost