---


tasks:

- name: "find _history"
  ansible.builtin.find:
    paths: /home
    file_type: files
    hidden: true
    patterns: '*_history'
    recurse: yes
  register: find_history

- name: "list _history files"
  debug: var="{{ item.path }}"
  with_items: "{{ find_history.files }}


730983