---
- hosts: docker01.lanathome.com
  become: yes
  gather_facts: false

  tasks:

  - name: correct typo error in /etc/rsyslog.conf
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^(.*)authpriv.\*.(.*)$'
      line: '\1authpriv.*\2'
      state: present
      backrefs: yes
