---

- hosts: all
  become: yes
  gather_facts: true

  vars:
    ntp_daemon: ntpd.service
    ntp_enabled: true
    chrony_daemon: chronyd.service
    chrony_enabled: true

  
  roles:
    #- roles/common-centos8
    - roles/monitoring
