# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


Vagrant.configure(2) do |config|
  config.vm.define "postfix" do |postfix|
    postfix.vm.box = "nrel/CentOS-6.5-x86_64"
    postfix.vm.hostname = "postfix"
    postfix.vm.network "private_network", ip: "192.168.34.51"
    postfix.vm.provider "virtualbox" do |vb|
  end
end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "postfix.yml"
  end
end
